version: '3'
services:
  app:
    container_name: worldcup
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
    networks:
      - worldcup-app

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: worldcup
      POSTGRES_USER: worldcup
      POSTGRES_PASSWORD: worldcup
    volumes:
      - postgres_data:/var/lib/postgresql/data
      #- ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - worldcup-app

volumes:
  postgres_data:

networks:
  worldcup-app:
    driver: bridge
